#服务端口
server:
  port: 8110

spring:
  #环境设置
  profiles:
    active: dev
  application:
    #服务名
    name: service-core
    #mysql数据库连接
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.78.161.13:3306/db2023_srb_core?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 

  cloud:
    nacos:
      discovery:
        server-addr: 120.78.161.13:8848 # nacos服务地址

  rabbitmq:
    host: 120.78.161.13
    port: 5672
    virtual-host: /ZlwRabbitMQHost
    username: admin
    password: 123456

  #redis数据库连接
  redis:
    #127.0.0.1 ---> localhost
    host: 120.78.161.13
    port: 6379
    #连接Redis-0号数据库
    database: 0
    #Redis的密码,默认为空
    password:
    #最大等待时间，超时则抛出异常，否则请求一直等待
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0

#mybatis
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # mybatis的 .xml配置文件映射
  mapper-locations: classpath:com/atguigu/srb/core/mapper/xml/*.xml
